run0edit: refactored inner script for clarity.
Signed-off-by: Daniel Hast <hast.daniel@protonmail.com>

diff --git a/files/system/usr/bin/run0edit b/files/system/usr/bin/run0edit
--- a/files/system/usr/bin/run0edit
+++ b/files/system/usr/bin/run0edit
@@ -1,7 +1,7 @@
 #!/bin/sh
 # ------------------------------------------------------------------------------
 # run0edit - edit a single file as root.
-# version 0.3.1-sb
+# version 0.3.2
 #
 # Please report issues at: https://github.com/HastD/run0edit/issues
 #
@@ -74,45 +74,64 @@ temp_filename=$(mktemp --tmpdir "${trunc_filename}.XXXXXXXXXX")
 
 # Inner script to be run with elevated privileges:
 script='\
-    if [ -f "$1" ]; then
-        if ! cp "$1" "$2"; then
-            echo "run0edit: failed to copy $1 to temporary file at $2";
-            exit 1;
-        fi
-    elif [ ! -e "$1" ]; then
-        if [ ! -d "$(dirname "$1")" ]; then
-            echo "run0edit: invalid argument: directory does not exist";
-            exit 1;
-        fi
-    else
-        echo "run0edit: invalid argument: not a regular file";
-        exit 1;
+    filename="$1"
+    tmpfile="$2"
+    editor="$3"
+
+    # If the file does not exist, ensure the directory exists.
+    if [ ! -e "$filename" ] && [ ! -d "$(dirname "$filename")" ]; then
+        echo "run0edit: invalid argument: directory does not exist"
+        exit 1
     fi
-    if ! run0 --user="$SUDO_UID" "$3" "$2"; then
-        echo "run0edit: failed to edit temporary file at $2";
-        exit 1;
+
+    # If the file exists, ensure it is a regular file.
+    if [ -e "$filename" ] && [ ! -f "$filename" ]; then
+        echo "run0edit: invalid argument: not a regular file"
+        exit 1
     fi
-    if [ -e "$1" ]; then
-        if cmp -s "$2" "$1"; then
-            echo "run0edit: $1 unchanged";
-        else
-            if ! cp "$2" "$1"; then
-                echo "run0edit: unable to write temporary file at $2 to $1";
-                exit 1;
+
+    # If the file exists, attempt to copy to the temp file.
+    if [ -f "$filename" ] && ! cp "$filename" "$tmpfile"; then
+        echo "run0edit: failed to copy $filename to temporary file at $tmpfile"
+        exit 1
+    fi
+
+    # Attempt to edit the temp file as the original user.
+    if ! run0 --user="$SUDO_UID" "$editor" "$tmpfile"; then
+        echo "run0edit: failed to edit temporary file at $tmpfile"
+        exit 1
+    fi
+
+    # If the target file exists and has been modified in the temp file, or
+    # if this is a new file that is non-empty, copy temp file to target.
+    if [ -f "$filename" ]; then
+        if ! cmp -s "$tmpfile" "$filename"; then
+            if ! cp "$tmpfile" "$filename"; then
+                echo "run0edit: unable to write temporary file at $tmpfile to $filename"
+                exit 1
             fi
-        fi
-    elif [ -s "$2" ]; then
-        touch "$1"
-        if ! cp "$2" "$1"; then
-            echo "run0edit: unable to write temporary file at $2 to $1";
-            exit 1;
+        else
+            echo "run0edit: $filename unchanged"
         fi
     else
-        echo "run0edit: $1 not created";
+        if [ -s "$tmpfile" ]; then
+            touch "$filename"
+            if ! cp "$tmpfile" "$filename"; then
+                echo "run0edit: unable to write temporary file at $tmpfile to $filename"
+                exit 1
+            fi
+        else
+            echo "run0edit: $filename not created"
+        fi
     fi'
 
 # Escape backslashes and double-quotes in paths to be passed to ReadWritePaths.
-escaped_dir=$(realpath -m "$directory" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g')
+if [ -e "$filename" ]; then
+    writable_path="$filename"
+else
+    writable_path="$directory"
+fi
+escaped_path=$(realpath -m "$writable_path" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g')
 escaped_temp_path=$(echo "$temp_filename" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g')
 
 set +e
@@ -136,7 +155,7 @@ run0 \
     --property="ProtectKernelTunables=yes" \
     --property="ProtectProc=noaccess" \
     --property="ProtectSystem=strict" \
-    --property="ReadWritePaths=\"$escaped_dir\" \"$escaped_temp_path\"" \
+    --property="ReadWritePaths=\"$escaped_path\" \"$escaped_temp_path\"" \
     --property="RestrictAddressFamilies=AF_UNIX" \
     --property="RestrictNamespaces=yes" \
     --property="RestrictRealtime=yes" \
