debug

diff --git a/.github/workflows/pull_request.yml b/.github/workflows/pull_request.yml
--- a/.github/workflows/pull_request.yml
+++ b/.github/workflows/pull_request.yml
@@ -101,6 +101,10 @@ jobs:
           CLICOLOR_FORCE: '1'
           GH_PR_EVENT_NUMBER: ${{ github.event.number }}
         run: |
+          if [ -z "$KERNEL_PRIVKEY" ]; then
+            echo "Missing KERNEL_PRIVKEY"
+            exit 1
+          fi
           BUILD_OPTS="--build-driver podman --squash"
           bluebuild build -v ${BUILD_OPTS} ${RECIPE_PATH}
           
